import type { CountryState } from './types';

export const initialCountries: CountryState[] = [
  {
    id: 'us',
    name: 'United States',
    flag: '🇺🇸',
    region: 'americas',
    interestRate: 5.25,
    inflation: 3.2,
    growth: 2.1,
    stability: 82,
    debtToGdp: 123,
    fxRate: 1.0,
    fxPrevious: 1.0,
    sentiment: 45,
    equityIndex: 100,
  },
  {
    id: 'eu',
    name: 'Eurozone',
    flag: '🇪🇺',
    region: 'europe',
    interestRate: 4.0,
    inflation: 2.8,
    growth: 0.8,
    stability: 75,
    debtToGdp: 90,
    fxRate: 1.08,
    fxPrevious: 1.08,
    sentiment: 20,
    equityIndex: 100,
  },
  {
    id: 'cn',
    name: 'China',
    flag: '🇨🇳',
    region: 'asia',
    interestRate: 3.45,
    inflation: 0.5,
    growth: 4.8,
    stability: 70,
    debtToGdp: 78,
    fxRate: 0.14,
    fxPrevious: 0.14,
    sentiment: -10,
    equityIndex: 100,
  },
  {
    id: 'br',
    name: 'Brazil',
    flag: '🇧🇷',
    region: 'emerging',
    interestRate: 11.75,
    inflation: 4.5,
    growth: 1.9,
    stability: 55,
    debtToGdp: 75,
    fxRate: 0.20,
    fxPrevious: 0.20,
    sentiment: 5,
    equityIndex: 100,
  },
  {
    id: 'jp',
    name: 'Japan',
    flag: '🇯🇵',
    region: 'asia',
    interestRate: 0.1,
    inflation: 3.0,
    growth: 1.0,
    stability: 88,
    debtToGdp: 260,
    fxRate: 0.0067,
    fxPrevious: 0.0067,
    sentiment: 15,
    equityIndex: 100,
  },
];
